### ISSUE TITLE
Question – result & entities in state

### ISSUE THREAD

**Issue by Hiswe** [itsmepetrov/redux-entities#1]
As I understand normalizr, it always produces a structure like that:

``` js
{
  result: {
    A: [/* array of A ids */],
    B: [/* array of B ids */],
  }
  entities: {
    A: { /* A ids: values */ },
    B: { /* B ids: values */ },
  },
}
```

Maintaining an array of `id` is good for keeping the order of the different elements (and also know, the length…)
In your combine method, it seems that reducers states are only the related Entities object.

Is there a reason for that?

**Comment by itsmepetrov** [comment]
Hi @Hiswe, sorry for the late response.

Yes, reducers states are only the related entities.

We don't store an array of ids (or provide reducers for that) because it depends on the particular implementation of application:

some users use pagination in lists and want to store ids by page:
```js
{
  byPage: {
    1: [1, 2, 3, 4, 5],
    2: [6, 7, 8, 9 ,10]
  }
}
```
other users want to store information about current loading status:
```js
{
  ids: [1, 2, 3, 4, 5],
  isLoading: true
}
```
and so on...

You should implement your own list reducer based on the application requirements.
